<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_MainImage</name>
   <tag></tag>
   <elementGuidId>41ec669e-0663-4a55-92b2-04f356873791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainImageContent > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MainImageContent']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>07820924-b604-499a-b59a-0b7fa48724fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>355</value>
      <webElementGuid>d4f20f53-5043-4f87-8501-2c06b9603819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/splash.gif</value>
      <webElementGuid>108db1fb-5687-4fd8-a707-516e9e37b402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>1ea5e029-3f82-4e34-8ef4-dfe8b1c2c716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>usemap</name>
      <type>Main</type>
      <value>#estoremap</value>
      <webElementGuid>e6f1ca38-5d0c-4017-86b1-476853ef5190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>350</value>
      <webElementGuid>e965d10b-f416-4f5d-a1df-3504436519aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainImageContent&quot;)/img[1]</value>
      <webElementGuid>5d31de18-3e00-471e-bbe0-21b1c39e8e94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainImageContent']/img</value>
      <webElementGuid>81bf299a-bf32-4191-aaac-aa2bbf0d44d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/img</value>
      <webElementGuid>43262d5c-0f91-45f7-ab47-001076753d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/splash.gif']</value>
      <webElementGuid>b7c441ff-5e24-41b2-99d8-a5d05ecb570b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
