<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sidebar_Dogs</name>
   <tag></tag>
   <elementGuidId>bb4e0545-3713-4d88-af28-87d52cd750c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SidebarContent > a:nth-of-type(2) > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SidebarContent']/a[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d7df8012-8429-4d54-bf0f-f244a956d12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/dogs_icon.gif</value>
      <webElementGuid>0e75962e-3996-467b-b7a1-f986c162cba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SidebarContent&quot;)/a[2]/img[1]</value>
      <webElementGuid>8b9e4efe-062f-4d90-93fd-6b9be244b471</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SidebarContent']/a[2]/img</value>
      <webElementGuid>7f4f0ab5-c7b4-4024-8f2f-afd6523c4d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a[2]/img</value>
      <webElementGuid>38876537-b87b-457b-9147-9176fca31162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/dogs_icon.gif']</value>
      <webElementGuid>131c1078-a030-49d0-9c8d-47be80bbf0f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
