<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Category</name>
   <tag></tag>
   <elementGuidId>59405730-9b48-4726-a010-f3913de2586a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;account.favouriteCategoryId&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='account.favouriteCategoryId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>10f167b7-78a2-4b2f-bfd4-510ead305e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account.favouriteCategoryId</value>
      <webElementGuid>fb9289c1-e948-45d1-9038-30dc1384a63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			FISHDOGSREPTILESCATSBIRDS
		</value>
      <webElementGuid>574a6388-ac72-4605-bb2f-19815f9e9473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/form[1]/table[3]/tbody[1]/tr[2]/td[2]/select[1]</value>
      <webElementGuid>09f4451f-d042-456c-846b-0305584d12c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='account.favouriteCategoryId']</value>
      <webElementGuid>6282d5d0-8269-45c3-8c31-7e0e2938c569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table[3]/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>cc621529-dbca-4229-8616-5f6b58233f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favourite Category:'])[1]/following::select[1]</value>
      <webElementGuid>78acf290-0b1f-462b-858c-8831614317aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language Preference:'])[1]/following::select[2]</value>
      <webElementGuid>b37d3d01-22e6-4f4e-87fc-8c0891995398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable MyList'])[1]/preceding::select[1]</value>
      <webElementGuid>f2adfe55-e1ba-4226-b785-d093b62033c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable MyBanner'])[1]/preceding::select[1]</value>
      <webElementGuid>9cf398d0-21d4-4406-b17a-a4e0ac4b4e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/select</value>
      <webElementGuid>e1b06fcb-5589-4f73-a252-7dfcf771ccda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'account.favouriteCategoryId' and (text() = '
			FISHDOGSREPTILESCATSBIRDS
		' or . = '
			FISHDOGSREPTILESCATSBIRDS
		')]</value>
      <webElementGuid>9ea58f96-bd44-4a84-a5e0-e4cc89e94522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
