<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Language</name>
   <tag></tag>
   <elementGuidId>63b3cd0f-218f-4fcb-a762-6ce838cb4e74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;account.languagePreference&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='account.languagePreference']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f4b0de09-32a1-4e07-ae6f-a6537f57ed32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account.languagePreference</value>
      <webElementGuid>5f73bbe8-58ff-447b-b0b1-fce2eac3256c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			englishjapanese
		</value>
      <webElementGuid>3e304857-492a-4857-b474-8138e56a31a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/form[1]/table[3]/tbody[1]/tr[1]/td[2]/select[1]</value>
      <webElementGuid>8ae25816-d667-4a56-86c4-2106df2b6c45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='account.languagePreference']</value>
      <webElementGuid>f8f72d0b-2a48-4a27-897b-8ca801583b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table[3]/tbody/tr/td[2]/select</value>
      <webElementGuid>fa5e4d9e-1455-4cee-b376-5b03daf03e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language Preference:'])[1]/following::select[1]</value>
      <webElementGuid>5e34e0f0-bb8f-4cd9-b55e-4fdd895540f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Information'])[1]/following::select[1]</value>
      <webElementGuid>2783ceea-921b-4f0f-a832-3a888a3b02de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favourite Category:'])[1]/preceding::select[1]</value>
      <webElementGuid>b9e282d9-641d-4e58-9344-4b7c4742f8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable MyList'])[1]/preceding::select[2]</value>
      <webElementGuid>44002d82-1816-4009-9bce-9d29f72cf747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1f15b349-e789-42c8-859c-4d8e5caf8854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'account.languagePreference' and (text() = '
			englishjapanese
		' or . = '
			englishjapanese
		')]</value>
      <webElementGuid>b16bc2d3-966d-40b7-aac4-8a023dcb5e4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
