<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_UpdateCart</name>
   <tag></tag>
   <elementGuidId>0de2abbf-5fcb-45bd-a3c5-c3e4736567f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;updateCartQuantities&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='updateCartQuantities']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a04f3d48-5fec-4442-a1a5-4ad235bbbad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>updateCartQuantities</value>
      <webElementGuid>61313028-0516-4e50-bbb4-a17eb2eb3660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5da73a05-74fc-4bef-820e-c7136afe7381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Update Cart</value>
      <webElementGuid>2efa0e65-5dc7-44bc-bc07-46bfb22724e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Cart&quot;)/form[1]/table[1]/tbody[1]/tr[3]/td[1]/input[1]</value>
      <webElementGuid>7ac454f6-dbc5-4219-b55e-1eb9cf9dce1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='updateCartQuantities']</value>
      <webElementGuid>119c346e-537c-49a1-803f-3a4dc3c6ce92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Cart']/form/table/tbody/tr[3]/td/input</value>
      <webElementGuid>c0fff682-386a-4666-8573-daf47e0e97ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>bde743d3-7f55-47d9-bde5-0c1ce3bda31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'updateCartQuantities' and @type = 'submit']</value>
      <webElementGuid>16b28531-5091-4b07-9d1f-81e25a9da8fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
