<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Country</name>
   <tag></tag>
   <elementGuidId>1516a85a-b467-4000-baaf-5edf0dd70706</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;order.billCountry&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='order.billCountry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a674af8-db54-4764-ab8e-9cba7738a13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>a9ddc211-eb14-4d3b-88f1-a88a87d85468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order.billCountry</value>
      <webElementGuid>eb8084fc-60b5-4584-8cb4-643ae5f860f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aeafade2-e057-4cd3-b6c3-0b670c76434b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>asdasddsa</value>
      <webElementGuid>7105b664-0e18-4fce-9cd2-48318fb37aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/form[1]/table[1]/tbody[1]/tr[13]/td[2]/input[1]</value>
      <webElementGuid>6958fba8-215b-4f0b-adbd-d6dfdc53cb01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='order.billCountry']</value>
      <webElementGuid>1193b6b8-59dc-4d28-89b3-749707351ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table/tbody/tr[13]/td[2]/input</value>
      <webElementGuid>ad542a92-5f9e-49c3-9f71-155a98248a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[2]/input</value>
      <webElementGuid>8d34ff53-970b-46a1-8082-f9c980e6a77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'order.billCountry' and @type = 'text']</value>
      <webElementGuid>00858c78-4600-49a9-9e34-f426a6d86946</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
