<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_OrderConfirmationMessage</name>
   <tag></tag>
   <elementGuidId>60bd4904-d7c3-43fb-95ba-46a870068940</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Content']/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>bfc54698-fbb8-47ab-aaa8-85ed9fb23caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you, your order has been submitted.</value>
      <webElementGuid>903a2b95-b2e2-47a5-9a64-3eb93e80d79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Content&quot;)/ul[@class=&quot;messages&quot;]/li[1]</value>
      <webElementGuid>195126d0-50a6-486c-bee2-47e9d7a16e4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Content']/ul/li</value>
      <webElementGuid>d453eceb-d05d-46bc-964e-de5b69c76abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[1]/following::li[1]</value>
      <webElementGuid>3fbb1262-925d-41d7-a2a7-2ccabd416097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[1]/following::li[1]</value>
      <webElementGuid>e1f20ddb-e128-4d5e-82ea-80b7605541c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return to Main Menu'])[1]/preceding::li[1]</value>
      <webElementGuid>ea3894ee-ee58-447c-b602-5fc99ad0f4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you, your order has been submitted.']/parent::*</value>
      <webElementGuid>d006af0b-a182-47df-8fd3-92aec613b70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>b418a747-2185-410b-af69-49f52fafa90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Thank you, your order has been submitted.' or . = 'Thank you, your order has been submitted.')]</value>
      <webElementGuid>df329a9c-bef8-4e9b-9618-0ee5186a6b97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
